### ISSUE TITLE
ALL NODES ARE GOING THROUGH VALIDATION

### ISSUE THREAD

**Issue by Jenos-Idanian** [TRON-US/go-btfs#634]
go-btfs version: 1.3.5-20c165c
Repo version: 9
System version: amd64/windows
Golang version: go1.14.6
Repo location: E:\BTFS

2020-08-11T15:51:43.333-0400    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: rpc error: code = Unknown desc = dial tcp 10.32.211.96:5432: i/o timeout
2020-08-11T15:51:43.344-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:51:43.357-0400    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync hosts: Failed to query hosts from Hub service: rpc error: code = Unavailable desc = Service Unavailable: HTTP status code 503; transport: received the unexpected content-type "text/html"
2020-08-11T15:51:43.359-0400    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync host stats: Failed to query stats from Hub service: rpc error: code = Unavailable desc = Service Unavailable: HTTP status code 503; transport: received the unexpected content-type "text/html"
2020-08-11T15:51:44.096-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:51:45.115-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:51:46.575-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:51:49.228-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:51:53.028-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:51:58.684-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
BTFS is up-to-date.
2020-08-11T15:52:06.461-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:52:15.479-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:52:32.780-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:52:54.688-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:53:31.000-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:53:58.015-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:54:43.179-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T15:56:09.658-0400    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rpc error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout

Many people on BTT Telegram are reporting the same issue. That their node is going through what seems to be the steps for validation. This has been happening from time to time on the 1.3.5, but it would always come back with a refresh.

Not the case this time. Was a patch pushed that has put us all through this process again?

**Comment by Crypto72** [comment]
Hi,

It's the same here, my host keeps validating all the time.

2020-08-11T00:44:00.418+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context d
eadline exceeded
2020-08-11T01:28:48.492+0100    ←[31mERROR←[0m  upload  upload/init.go:303      failed to download shard QmNfEWRC6KAuVR2
dp6igtN5qvjUWK1VwGr6sRL7TngkzYY from file Qmbbf9U7pXbgX9nHJ86jFe7dgvktEWvmAy4YZCkuGPK82n with contract id 1d7cc989-6d5e-
47aa-81a2-dedb4e67fa5d,47bc2179-3df9-4e89-8d11-e30445d9e6b7: [failed to get block for QmNNarbqHAeAb6UkGvrYodX9PVt9XGL7TX
9XK4ei1U9XRi: context deadline exceeded]
2020-08-11T05:42:20.521+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context d
eadline exceeded
2020-08-11T06:22:03.733+0100    ←[31mERROR←[0m  upload  upload/init.go:303      failed to download shard QmUes5zeignL7nS
CttkxDtUUu72gAz6hVpJ8eJWHaYrweu from file QmaS8vh7u5fYBfBL5ZAMtjaCe5VJE8FSzMF3o2raoy9by5 with contract id 805481d8-1cc8-
4c15-b7e4-18246c6df9f7,36d0edff-d149-4ba1-af0d-489087d8433c: [failed to get block for QmWnCwDbQ3tDmj3SY1DUNsi67kMRDuYkEF
CWs9qWMAvJDj: context deadline exceeded]
2020-08-11T06:27:50.045+0100    ←[31mERROR←[0m  upload  upload/init.go:303      failed to download shard QmVyiydNLJuzmiG
YxTKYEg4qJwfmJiVYtykQMB95Bcj5aN from file QmXStxgEoprqjx5dDEy1YPDwf1cvG212khJLMv2A65jo3P with contract id 55144961-3d44-
4b3f-a95a-9845d73530e1,11821c03-767c-4c9a-8e87-4168fa2fa74f: [failed to get block for QmVyiydNLJuzmiGYxTKYEg4qJwfmJiVYty
kQMB95Bcj5aN: context deadline exceeded]
2020-08-11T06:32:23.515+0100    ←[31mERROR←[0m  upload  upload/init.go:303      failed to download shard QmZcKbNqaYv9ivB
WWZumjwcumG4L35wc3zBYFkfibZE6Y1 from file QmPhxExXxdfhqoX7Jth6S3pMCCbG3gUTEDtECNywhKfGFa with contract id b7e44e26-ec17-
4139-aac7-07a7fdd6a94d,adb57bdf-d055-4477-aa4b-fcb293e29d6f: [failed to get block for QmZcKbNqaYv9ivBWWZumjwcumG4L35wc3z
BYFkfibZE6Y1: context deadline exceeded]
BTFS is up-to-date.
2020-08-11T10:46:14.166+0100    ←[31mERROR←[0m  upload  upload/init.go:303      rpc error: code = Unknown desc = questio
n not ready for renterPid 16Uiu2HAkyXPo3XG93EjqmiKQum7QxhimrxEEvRTsygsA1y4Sh743 fileHash QmRNURMLgaQ4UkJoJS8yuT1w8mcVXQP
uXsot84GNB4tzzt shardHash QmUH9GWgNxWA6TYi9p1KduKn1dzQdaUJqHSQfDb9vtkzB6 contractId a12a2af3-32a6-4964-be60-c9db8d9f1086
,7395d089-49b9-4ced-9b3c-6fb13b91cc28 , process will be continue in p2pCall
2020-08-11T16:45:44.113+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context d
eadline exceeded
2020-08-11T17:46:00.961+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context d
eadline exceeded
2020-08-11T18:18:37.810+0100    ←[31mERROR←[0m  upload  upload/init.go:303      failed to download shard QmQvS2mhPCLUtW5
XYfz4nGC6gDPDNHx8kJVJsYTRTNSBbx from file QmaUhjfWa2396Aas1F8DYiyAeCKSUhUEPrehpjHS6SEpHj with contract id d9e0b2ac-53c1-
4e2b-b6b9-7d8fe9fcda70,dc6c717a-8191-4ca1-b654-c33217d62552: [failed to get block for QmRtYaPYjXbAoA3MfoaioysryTsziiDcp8
JHgk1Uv742a5: context deadline exceeded]
2020-08-11T18:25:04.221+0100    ←[31mERROR←[0m  upload  upload/init.go:303      failed to download shard QmdJSi5FyxLvenc
2UWHx8vn8Wmmy6S1BSqpDPofVamnxTh from file QmUq8oUDF9FhUzhM4cHVxhSLqPNVLgXh1bXpLLgsXicT49 with contract id 364ac7ac-1bbf-
4c2f-830c-7c3b6b4dc749,e0c6df5a-4a7a-4b7f-9e40-a8b32015c0ac: [failed to get block for QmNoS2sMSGpxogJpZXv9YkdvDTVdqQiPJQ
orurjquHrcsE: context deadline exceeded]
2020-08-11T18:40:54.729+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context d
eadline exceeded
2020-08-11T19:04:04.110+0100    ←[31mERROR←[0m  upload  upload/init.go:303      failed to download shard QmV5EiZYDLrESAB
GG7kobmiFTRvFRw3xiD3zQSWjhDESzk from file QmQZiYvzCBmbRwcE5S8JdPs5h41kgG5Cw4TXSXJFMrKGMc with contract id dafe8735-f33f-
400d-82ce-5034d4934c80,7c9278dc-4966-44d6-bad0-d708b04c5d9f: [failed to get block for QmToMvyBAc1gUNTcsYfAaS8mV1HsRjPifY
KokXrenfqNvv: context deadline exceeded]
2020-08-11T20:10:17.876+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:10:18.800+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:10:20.254+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:10:21.780+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:10:23.081+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:10:26.824+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:10:31.400+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:10:37.395+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:10:45.974+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:11:03.904+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:11:25.193+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:11:54.999+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:12:30.390+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:13:45.774+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:14:59.137+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:16:10.467+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:16:45.294+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:18:05.883+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:19:24.545+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:25:17.859+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:25:17.865+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync hosts: Failed to query ho
sts from Hub service: rpc error: code = Unavailable desc = Service Unavailable: HTTP status code 503; transport: receive
d the unexpected content-type "text/html"
2020-08-11T20:25:17.866+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync host stats: Failed to que
ry stats from Hub service: rpc error: code = Unavailable desc = Service Unavailable: HTTP status code 503; transport: re
ceived the unexpected content-type "text/html"
2020-08-11T20:25:17.869+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: rpc error
: code = Unknown desc = dial tcp 10.32.211.96:5432: i/o timeout
2020-08-11T20:25:18.522+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:25:19.581+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:25:20.999+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:25:22.707+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:25:27.870+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:25:32.754+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:25:37.529+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:25:48.735+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:25:56.931+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:26:07.137+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:26:35.290+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:27:35.045+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:28:27.977+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:29:22.777+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:30:04.386+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:31:30.613+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:32:05.035+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:33:33.739+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:34:23.644+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:40:17.862+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:40:18.667+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:40:19.419+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:40:20.866+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:40:23.084+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:40:25.319+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:40:30.497+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:40:34.004+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:40:45.848+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:40:56.573+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:41:21.525+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:41:38.581+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:42:36.070+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:43:57.344+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:45:21.531+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:46:36.066+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:47:26.434+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:48:29.872+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:49:34.541+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:55:17.858+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:55:17.860+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync host stats: Failed to que
ry stats from Hub service: rpc error: code = Unavailable desc = Service Unavailable: HTTP status code 503; transport: re
ceived the unexpected content-type "text/html"
2020-08-11T20:55:18.902+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:55:20.065+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:55:21.584+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:55:22.983+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:55:25.066+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:55:27.426+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:55:30.820+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:55:41.750+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:55:52.440+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:56:19.402+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:56:40.331+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:57:37.317+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:58:14.637+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T20:59:39.734+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T21:00:55.962+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T21:01:40.286+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout
2020-08-11T21:02:33.141+0100    ←[31mERROR←[0m  spin    spin/analytics.go:209   failed to send data to status server: rp
c error: code = Unknown desc = dial tcp 10.32.126.85:5432: i/o timeout

**Comment by taiyangc** [comment]
Thanks we are investigating.

**Comment by henrybug** [comment]
Similar issue here for 2 hosts

**Comment by taiyangc** [comment]
This issue has been resolved, please refer to #624 for the original validation bug.

**Comment by Jenos-Idanian** [comment]
Thanks!!!!

**Comment by Crypto72** [comment]
Hi

I stopped the btfs daemon, restarted my host and then the VALIDATION cycle started to run again and again (randomly without an apparent logic) and I got various errors displayed in the daemon console. So, I guess the issues are not solved, isn't it?

T:\btfs>btfs.exe daemon
Initializing daemon...
go-btfs version: 1.3.5-20c165c
Repo version: 9
System version: amd64/windows
Golang version: go1.14.6
Repo location: T:\btfs
Node ID: 16Uiu2HAm37e4LJ5RCtcVDrESGMS1oLU1B73eTEV2qLLY23HxbtSh
Swarm listening on /ip4/127.0.0.1/tcp/1234
Swarm listening on /ip4/169.254.107.2/tcp/1234
Swarm listening on /ip4/169.254.114.255/tcp/1234
Swarm listening on /ip4/169.254.202.243/tcp/1234
Swarm listening on /ip4/169.254.40.171/tcp/1234
Swarm listening on /ip4/169.254.70.232/tcp/1234
Swarm listening on /ip4/192.168.0.17/tcp/1234
Swarm listening on /ip6/::1/tcp/1234
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/1234
Swarm announcing /ip4/169.254.107.2/tcp/1234
Swarm announcing /ip4/169.254.114.255/tcp/1234
Swarm announcing /ip4/169.254.202.243/tcp/1234
Swarm announcing /ip4/169.254.40.171/tcp/1234
Swarm announcing /ip4/169.254.70.232/tcp/1234
Swarm announcing /ip4/192.168.0.17/tcp/1234
Swarm announcing /ip4/90.201.122.128/tcp/1234
Swarm announcing /ip6/::1/tcp/1234
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.
2020-08-12T04:10:53.594+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context deadline exceeded
2020-08-12T04:10:53.589+0100    ←[31mERROR←[0m  upload  upload/init.go:303      failed to download shard QmTpXxBACajAB3QtMvL7Zvy4zSF9oXm6UqTbbBkaNG716k from file QmNYXHgdJd9BxME2Ads9qyLuCBZW3juYzmGaAJmArwJL8h with contract id 9c4185df-9f18-
4189-a664-7329b67f3586,085b061b-a70b-4a6c-9ea9-05c8ce43bc68: [failed to get block for QmSfBi43HRBCreuXtALFpsVN5wSTdm9kXmcpqpc98RtdVi: context deadline exceeded]
2020-08-12T04:57:56.650+0100    ←[31mERROR←[0m  upload  upload/init.go:303      rpc error: code = Unknown desc = question not ready for renterPid 16Uiu2HAkyXPo3XG93EjqmiKQum7QxhimrxEEvRTsygsA1y4Sh743 fileHash QmdpQefnTMFG7VDRbQnkrBmZNYkeGGxwoBPjX22bYBhrq6 shardHash QmSUZUchW2tpcjpiTFyjy9rRWR22Dti7gfUJyFYd6YutP1 contractId b0d4f196-80b6-40de98ba-530aa7c0cba7,e5f648bd-f82f-4646-9391-a4dbf1006faf , process will be continue in p2pCall
2020-08-12T08:13:36.809+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context deadline exceeded
2020-08-12T08:55:32.803+0100    ←[31mERROR←[0m  upload  upload/init.go:303      failed to download shard QmcSAWMJFnsUuH4Gge8ED6Y1coTs4LKBK59uQ56cqH2Gqf from file QmXLtZseZ7gNEXohRLEv9hggZx4STug7zo2CyD1or65aAp with contract id 007cadb8-8d4f-
4159-940a-c792eed66a1c,654b7174-b6c4-4734-9462-126d3cff85b7: [failed to get block for QmTEGHRLNGMvPfwKxUqdWsj7ViC1kugcMRSajwEytg6McD: context deadline exceeded]

Have a great day!

**Comment by taiyangc** [comment]
@Crypto72 We are tracking this problem in #624 please follow that thread for updates.
