### ISSUE TITLE
No new contracts on any of my nodes and no payment received/date stuck

### ISSUE THREAD

**Issue by steelvirus** [TRON-US/go-btfs#967]
I have several nodes running, all working fine until a few weeks ago, when they stopped getting contracts. All of them have a host-score of 10 and have been online for some time. I looked at the documentation and the pricing-structure changed from 7680 to 3840, so I changed that, but that did not do anything. 

Also I have not received any payments yet, and the payment date is stuck. (One node on the 21.03). The daemon did not print any unusual errors.

Two of my nodes:
16Uiu2HAmMooZPTKFiENR3ttesUncMYKJVCbRoesZXmnN5JwsPCPh
16Uiu2HAm1kE7H3izRP27Wie113q7Evb4JUP6sMUyS62c7Tk4ajT7

The top one is my oldest node and the bottom one my newest.

Thank you in advance.

**Comment by thatalbertaguy** [comment]
I think we have similar problems mine was stuck at 187 contracts and then it doubled and storage went to 0 . Not sure what happened . I only have one node working vs 2 but sounds like maybe a bigger issue 

https://github.com/TRON-US/go-btfs/issues/964

**Comment by kmoore134** [comment]
Confirmed I'm seeing the same issues here, payment date stuck, no contracts for a while despite a 10 score. Restarted the daemon with no change.

**Comment by thatalbertaguy** [comment]
Did either of you check your rental rate ? I think it’s dropped to 3840 /tb but default is staying at 7800

**Comment by kmoore134** [comment]
Oh, interesting.  Is that default published anywhere? I changed it now,  will see if it makes any difference.

**Comment by thatalbertaguy** [comment]
I stumbled upon this at the bottom 

https://docs.btfs.io/docs/what-is-btfs

**Comment by laipogo** [comment]
The default price is now 3840/tb. And the text will be fixed in next release.

**Comment by steelvirus** [comment]
> I think we have similar problems mine was stuck at 187 contracts and then it doubled and storage went to 0 . Not sure what happened . I only have one node working vs 2 but sounds like maybe a bigger issue 
> 
> https://github.com/TRON-US/go-btfs/issues/964
    Why did you close my issue? Changing the price did not fix my problems, they still persist.

**Comment by steelvirus** [comment]
> The default price is now 3840/tb. And the text will be fixed in next release.


Why did you close the issue? My problems still persist even after changing the pricing.

**Comment by laipogo** [comment]
sorry, i thought changing the price would fix your issue.

**Comment by steelvirus** [comment]
> sorry, i thought changing the price would fix your issue.

Thank you.

**Comment by Sophia-yu-kk** [comment]
Renters will randomly select Hosts by their score and geo when they upload files. Since the number of eligible Hosts is large (details can be found at https://scan.btfs.io), we cannot guarantee the number of contracts for each Host. However, with the expansion of the BTFS community and use cases, more contracts will come. 
 
When a Renter uploads a file to the BTFS network, he needs to pay BTT as storage fee to the Host who stores the file for him. The current default storage price is 3840 BTT/TiB/month, i.e. if a Host node stores a file of 1 TiB size for a full month, it will receive 3840 BTT in revenue. This revenue will be paid out at the end of the corresponding file storage contract, or on a monthly basis for the previous month, as shown in the "Revenue to date" area of the Host tab in the Host UI. The current payout may be slightly later than the "next payment date" shown in this area.

**Comment by steelvirus** [comment]
@laipogo I'm slowly getting new contracts, so that issue seems to have been resolved, but I still have not received payment and it's been almost a month.

If you believe this is not an problem and will resolve on its own, please close this issue.

Thank you for your help, I appreciate it!

**Comment by laipogo** [comment]
Still working on it, thanks for your patience.

**Comment by dellme** [comment]
> Still working on it, thanks for your patience.

Hello,

node 16Uiu2HAmGvRDmE6n4Zkwr8EMTMSKgfD6KXzd1YyEPBLPenavrYP1 has same problem. No contract  , HOST SCORE 10 

Please fix it

Thank you

**Comment by murthydevarakonda** [comment]
Hello, node ID 16Uiu2HAm3Ps5H2hRSQkdnWaKnLC729gCGb8qpDwzVk4YNBT3Wf1R

I have no contracts and payment got stuck for more than two months. Let me know when you will resolve this issue.

Thank you.

**Comment by Mortuus-Medicus** [comment]
Hi there, my node (ID: 16Uiu2HAkuworFrTjB7oJ5FkX6j3LvaWkUnkaHqMt1ExtMSKQV1Qq) has been active for some months now, the hoste score is 10/10, but I've still not received any contracts, my GEO location is Slovenia, Europe.

Am I doing something wrong, or is it normal to just never get any contrats? 
I'm offering 4TB of space, and once we'll be able to select multiple drives, I'll probably add a few more TB, that is if I'll ever even get a contract...
Thank you for any help possible!

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
